# This file was generated by GoReleaser. DO NOT EDIT.
cask "healthchecksio-cli" do
  name "healthchecksio-cli"
  desc "A simple CLI for healthchecks.io."
  homepage "https://github.com/sosheskaz/healthchecksio-cli"
  version "1.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "healthchecksio-cli"
  bash_completion "completions/bash_completion.sh"
  zsh_completion "completions/zsh_completion.sh"
  fish_completion "completions/fish_completion.fish"

  on_macos do
    on_intel do
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Darwin_x86_64.tar.gz"
      sha256 "e62d6a7f853176bbea433ca3aeded8caa9a39ffb108ad249a545da312939b6cf"
    end
    on_arm do
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Darwin_arm64.tar.gz"
      sha256 "9a4db2fe812343de6bcab9f74b2b88823ecc3d0824c0124cc240ed0697aeb3e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Linux_x86_64.tar.gz"
      sha256 "6fcaba683818d103ee8f1ea10819f536167d0d6592a76c36291cbd7060e8fac5"
    end
    on_arm do
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Linux_arm64.tar.gz"
      sha256 "7dc6c7cd9bb7fb6a68c37a10a4aa274666af2542aea06e5355cf2fb22918bf07"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/foo"]
    end
  end

  # No zap stanza required
end
