# This file was generated by GoReleaser. DO NOT EDIT.
cask "healthchecksio-cli" do
  version "1.4.2"

  on_macos do
    on_intel do
      sha256 "95f6aee50df68927bf82353af7491efe2fa0a536f7ffff1ba1d5b803d3ace4fb"
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e6d43177b05fec56a8e813f36dd5e285027328b5a5301fd6164fda196d8e3ab5"
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1a2787060e7bde6dfd2c79c304ba5bf394fe980acf6afedb5adad8f99fed0e52"
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b8f3871b4d3201317ca4072a8f6ebf2bff01c2ead69be15fb903f3a187b7ba34"
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Linux_arm64.tar.gz"
    end
  end

  name "healthchecksio-cli"
  desc "A simple CLI for healthchecks.io."
  homepage "https://github.com/sosheskaz/healthchecksio-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "healthchecksio-cli"
  bash_completion "completions/bash_completion.sh"
  fish_completion "completions/fish_completion.fish"
  zsh_completion "completions/zsh_completion.sh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/healthchecksio-cli"]
    end
  end

  # No zap stanza required

end
