# This file was generated by GoReleaser. DO NOT EDIT.
cask "healthchecksio-cli" do
  name "healthchecksio-cli"
  desc "A simple CLI for healthchecks.io."
  homepage "https://github.com/sosheskaz/healthchecksio-cli"
  version "1.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "healthchecksio-cli"
  bash_completion "completions/bash_completion.sh"
  zsh_completion "completions/zsh_completion.sh"
  fish_completion "completions/fish_completion.fish"

  on_macos do
    on_intel do
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Darwin_x86_64.tar.gz"
      sha256 "0c292d6dbd275a3bd558b98e3459b61366925de82aadff9bb2a35658a2a2ee61"
    end
    on_arm do
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Darwin_arm64.tar.gz"
      sha256 "abd7ba1a689b1094a48f46a560d2e9609c55b6d5e67cc815cf1334bd92f2a3d0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Linux_x86_64.tar.gz"
      sha256 "bfcae8de16c084ef3897bf2e0409ebcdcab0885f01d659b93a5911a189e7ae08"
    end
    on_arm do
      url "https://github.com/sosheskaz/healthchecksio-cli/releases/download/v#{version}/healthchecksio-cli_Linux_arm64.tar.gz"
      sha256 "d559cfcb2004c0b1450c97178c53e01238e6556e22acb4973174d4aac3ba77d0"
    end
  end

  # No zap stanza required
end
