# This file was generated by GoReleaser. DO NOT EDIT.
cask "swys" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "fa463e9363e844769a28d68a932c7705b62819bb7aae5cc86b2f5355db20820b"
      url "https://github.com/sosheskaz/swys/releases/download/v#{version}/swys_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "62397f0328ae1b4fd6ff2b240e477883fa769f1be59a6ca695326332ee5b4be4"
      url "https://github.com/sosheskaz/swys/releases/download/v#{version}/swys_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "94e9ed61e24fcbf38b2a222902aa9bccf162f89c5381963c276a32b4e90f0b93"
      url "https://github.com/sosheskaz/swys/releases/download/v#{version}/swys_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "84b3e3456d32f7c57f690298d7a96e0834d93c6d48fffb014fa49673707cb849"
      url "https://github.com/sosheskaz/swys/releases/download/v#{version}/swys_Linux_x86_64.tar.gz"
    end
  end

  name "swys"
  desc "Sysadmin's Swiss Army knife"
  homepage "https://github.com/sosheskaz/swys"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swys"
  bash_completion "completions/swys.bash"
  fish_completion "completions/swys.fish"
  zsh_completion "completions/swys.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/swys"]
    end
  end

  # No zap stanza required
end
