# This file was generated by GoReleaser. DO NOT EDIT.
cask "swys" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "445070802fe8b35ef45cd95410c57ab337674dce6600ae73b6eca8cacda51c96"
      url "https://github.com/sosheskaz/swys/releases/download/v#{version}/swys_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ae1b91709b53d42f82e4fcd016ddc256e934d50bbe54238ea5f9fc320c1d7cd7"
      url "https://github.com/sosheskaz/swys/releases/download/v#{version}/swys_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "efad5da870e9a75f3520b25c1fc237f329646d49ec727ff9ece20462e15bf8a1"
      url "https://github.com/sosheskaz/swys/releases/download/v#{version}/swys_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "5ba1a8f8ab8058f72f269f1c3ec2c4e00b4c348e836d5d2ead539044eb5bcc66"
      url "https://github.com/sosheskaz/swys/releases/download/v#{version}/swys_Linux_x86_64.tar.gz"
    end
  end

  name "swys"
  desc "Sysadmin's Swiss Army knife"
  homepage "https://github.com/sosheskaz/swys"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "swys"
  bash_completion "completions/swys.bash"
  fish_completion "completions/swys.fish"
  zsh_completion "completions/swys.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/swys"]
    end
  end

  # No zap stanza required
end
